### config.toml
title = "GSEBeLux"
baseURL = "https://gsebelux.eu/"
theme = "gsebelux"
languageCode = "en-us"
dataDir = "data"
assetDir = "assets"
PaginatePath = "blog"
sectionPagesMenu = "main"
buildDrafts = false
pygmentsUseClasses = true
enableGitInfo = true
enableRobotsTXT = true

[outputs]
section = [ "HTML", "Calendar", "RSS" ]

[outputFormats]
[outputFormats.RSS]
	mediatype = "application/rss"
	baseName = "feed"
	suffix = "xml"
