version: 2
jobs:
  production:
    docker:
      - image: cibuilds/hugo:0.55.1
    steps:
      - checkout
      - run:
          name: "Build site to GH Pages"
          command: bin/deploy.sh

  build:
    docker:
      - image: cibuilds/hugo:0.55.1
    working_directory: ~/gsebelux
    steps:
      - checkout
      - run:
          name: "Run Hugo"
          command: make
      - persist_to_workspace:
          root: .
          paths:
            - public

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
  nightly:
    triggers:
      - schedule:
          cron: "1 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
  
